export const help = {
  showHelp(topic) {
    const helpContent = {
      risk_scores: '<h4>Risk Scoring Guide</h4><p>Rate each dimension from 1 (low risk) to 5 (critical risk):</p><ul><li><strong>Patient Safety (25%)</strong> - Could incorrect output harm patients? Score 5 if errors could cause mortality.</li><li><strong>Bias/Fairness (20%)</strong> - Does the system perform equitably across demographic groups?</li><li><strong>Data Privacy (15%)</strong> - How much PHI is accessed? What are de-identification measures?</li><li><strong>Clinical Validity (15%)</strong> - Is there peer-reviewed evidence supporting the AI\'s claims?</li><li><strong>Cybersecurity (15%)</strong> - What is the attack surface? Model poisoning risk?</li><li><strong>Regulatory (10%)</strong> - Are there compliance gaps with FDA, HIPAA, state laws?</li></ul>',
      asset_categories: '<h4>AI Asset Categories</h4><ul><li><strong>Clinical Decision Support</strong> - Tools that assist clinicians in making care decisions</li><li><strong>Diagnostic Imaging</strong> - AI-powered radiology, pathology, or other imaging analysis</li><li><strong>Predictive Analytics</strong> - Patient risk prediction, readmission models, sepsis alerts</li><li><strong>NLP Extraction</strong> - Natural language processing for clinical notes, coding</li><li><strong>Operational</strong> - Scheduling, resource optimization, supply chain</li><li><strong>Administrative</strong> - Prior auth, claims processing, documentation</li><li><strong>Revenue Cycle</strong> - Coding optimization, denial prevention, payment prediction</li></ul>',
      risk_tiers: '<h4>Risk Tier Definitions</h4><ul><li><strong>Critical</strong> - Direct life-safety impact. Requires Board-level oversight, continuous monitoring, and annual third-party audit.</li><li><strong>High</strong> - Significant clinical or privacy impact. Requires executive sponsor, quarterly reviews, and bias testing.</li><li><strong>Moderate</strong> - Indirect clinical impact or operational significance. Requires designated owner and semi-annual review.</li><li><strong>Low</strong> - Administrative or minimal clinical impact. Standard documentation and annual review.</li></ul>',
      vendor_scoring: '<h4>Vendor Scoring Methodology</h4><p>Each dimension is rated 1-5 and weighted:</p><ul><li>Transparency: 15%</li><li>Bias Testing: 25%</li><li>Security: 25%</li><li>Data Practices: 20%</li><li>Contractual: 15%</li></ul><p>Overall score (0-100): Below 40 = Rejected, 40-60 = Conditional, Above 60 = Approved</p>',
    };
    const content = helpContent[topic] || '<p>No help available for this topic.</p>';
    App.openModal('Help', `<div class="kb-body">${content}</div>`, '');
  },
};
